language: node_js
node_js:
- '9'
before_script:
- npm run lint
- npm run build
deploy:
  provider: npm
  email: contact@therealtbs.com
  skip_cleanup: true
  api_key:
    secure: M8vEvgK7QDeb0vkKNqOJeOupiyYE6qLw95WnLu5+meZfp7q1OEjaIVHE5O6AaVuZfeM8qJ22HdPNYZBIcUXJA3PLo+Ns9iU1EmW8qRrt8ItPagei84LCzA30KCvJr9gnfbdhqcqKmu7GvqGGc4MsPlTMpNw+gMHoq53mSNmawE9w287uwmeYLBVuPjrRL89Sq4ZfpjxiR/k4CJl+QUBk7bnb0p56eArgJn1IFnfFFNuPbMRHplN6IFxzsjAsbA6E0dCjL/bY5fLlHiWX+WiBANroud0AUALIVGJWwyfH8ZitL8DZniPqhQwBmNwSLaquaH4kBIs6QtZV1Rmk7rDmmqfz9CpelnpRdiYpPseRE8x2uaiiJxhaehRVhzRr+LJTPHp6E6cIbBTP49lDsO4jPopdUCs1ro/2kNDYcSgbmX+f9rn09KPyosj5cNv7sesagqlObGMCIJxFHp2C8BjKEbqc49jylZdn+4oOu1dZYJaILWhOKZOEZ9H7cZVZdQRD8eV/0saZ7Rua8S9dsRohyY6bw0UkX1aUkVA9ghzp3OHcybEci41gsiPrOO93oA8/NuRFsXooKkJhfoYxWB5pqmm3d65540fh26BC9fILm3jReqkZgSb87zt+tnnEyFyxl5oxhp/djiZ4H80f9vb7f19y3QFFOisi7wg+IVljbvE=
  on:
    tags: true
    repo: therealtbs/react-adjustable-gauge
